title: CFPs
description: Countdowns to conferences I am interested in
author: Ulrich Aïvodji

domain: "kekeli-lab.github.io"
baseurl: ""

twitter_username: umaivodj
twitter_hashtag: 
github_username: kekeli-lab
github_repo: cfps

markdown: kramdown
ga_id: 

include: ['_pages']